experimento: expC01_Prueba07
dir_experimento: ~/buckets/b1/exp/expC01_Prueba07
dir_dataset: ~/buckets/b1/datasets/
carpeta_logs: logs/
carpeta_bayesiana: Archivos Bayesiana/
carpeta_kaggle: Kaggle/
carpeta_kaggle_ensamble: Kaggle_Promediado/
carpeta_graficos: Plots/
carpeta_entregables: Entregables/
semilla_primigenia: 200003.0
semillas_ensemble:
- 200003.0
- 300007.0
- 400009.0
- 500009.0
- 600011.0
- 314159.0
- 102191.0
- 111109.0
- 230101.0
- 100129.0
train:
- 202101.0
- 202102.0
train_final:
- 202101.0
- 202102.0
future: 202104.0
train_final_kaggle:
- 202101.0
- 202102.0
- 202103.0
- 202104.0
entrega_kaggle: 202106.0
semilla_kaggle: 314159.0
cortes:
- 0.0
- 100.0
- 200.0
- 300.0
- 400.0
- 500.0
- 600.0
- 700.0
- 800.0
- 900.0
- 1000.0
- 1100.0
- 1200.0
- 1300.0
- 1400.0
- 1500.0
- 1600.0
- 1700.0
- 1800.0
- 1900.0
- 2000.0
- 2100.0
- 2200.0
- 2300.0
- 2400.0
- 2500.0
- 2600.0
- 2700.0
- 2800.0
- 2900.0
- 3000.0
- 3100.0
- 3200.0
- 3300.0
- 3400.0
- 3500.0
- 3600.0
- 3700.0
- 3800.0
- 3900.0
- 4000.0
- 4100.0
- 4200.0
- 4300.0
- 4400.0
- 4500.0
- 4600.0
- 4700.0
- 4800.0
- 4900.0
- 5000.0
- 5100.0
- 5200.0
- 5300.0
- 5400.0
- 5500.0
- 5600.0
- 5700.0
- 5800.0
- 5900.0
- 6000.0
- 6100.0
- 6200.0
- 6300.0
- 6400.0
- 6500.0
- 6600.0
- 6700.0
- 6800.0
- 6900.0
- 7000.0
- 7100.0
- 7200.0
- 7300.0
- 7400.0
- 7500.0
- 7600.0
- 7700.0
- 7800.0
- 7900.0
- 8000.0
- 8100.0
- 8200.0
- 8300.0
- 8400.0
- 8500.0
- 8600.0
- 8700.0
- 8800.0
- 8900.0
- 9000.0
- 9100.0
- 9200.0
- 9300.0
- 9400.0
- 9500.0
- 9600.0
- 9700.0
- 9800.0
- 9900.0
- 10000.0
- 10100.0
- 10200.0
- 10300.0
- 10400.0
- 10500.0
- 10600.0
- 10700.0
- 10800.0
- 10900.0
- 11000.0
- 11100.0
- 11200.0
- 11300.0
- 11400.0
- 11500.0
- 11600.0
- 11700.0
- 11800.0
- 11900.0
- 12000.0
- 12100.0
- 12200.0
- 12300.0
- 12400.0
- 12500.0
- 12600.0
- 12700.0
- 12800.0
- 12900.0
- 13000.0
- 13100.0
- 13200.0
- 13300.0
- 13400.0
- 13500.0
- 13600.0
- 13700.0
- 13800.0
- 13900.0
- 14000.0
- 14100.0
- 14200.0
- 14300.0
- 14400.0
- 14500.0
- 14600.0
- 14700.0
- 14800.0
- 14900.0
- 15000.0
- 15100.0
- 15200.0
- 15300.0
- 15400.0
- 15500.0
- 15600.0
- 15700.0
- 15800.0
- 15900.0
- 16000.0
- 16100.0
- 16200.0
- 16300.0
- 16400.0
- 16500.0
- 16600.0
- 16700.0
- 16800.0
- 16900.0
- 17000.0
- 17100.0
- 17200.0
- 17300.0
- 17400.0
- 17500.0
- 17600.0
- 17700.0
- 17800.0
- 17900.0
- 18000.0
- 18100.0
- 18200.0
- 18300.0
- 18400.0
- 18500.0
- 18600.0
- 18700.0
- 18800.0
- 18900.0
- 19000.0
- 19100.0
- 19200.0
- 19300.0
- 19400.0
- 19500.0
- 19600.0
- 19700.0
- 19800.0
- 19900.0
- 20000.0
trainingstrategy:
  undersampling: 0.5
hyperparametertuning:
  xval_folds: 5.0
  hs:
    pars:
      num_leaves:
        id: num_leaves
        type: integer
        len: 1
        lower: 10
        upper: 2048
        values: ~
        cnames: ~
        allow.inf: no
        has.default: no
        default: ~
        trafo: ~
        requires: ~
        tunable: yes
        special.vals: []
      num_iterations:
        id: num_iterations
        type: integer
        len: 1
        lower: 50
        upper: 3000
        values: ~
        cnames: ~
        allow.inf: no
        has.default: no
        default: ~
        trafo: ~
        requires: ~
        tunable: yes
        special.vals: []
      learning_rate:
        id: learning_rate
        type: numeric
        len: 1
        lower: 0.01
        upper: 0.5
        values: ~
        cnames: ~
        allow.inf: no
        has.default: no
        default: ~
        trafo: ~
        requires: ~
        tunable: yes
        special.vals: []
      feature_fraction:
        id: feature_fraction
        type: numeric
        len: 1
        lower: 0.1
        upper: 1.0
        values: ~
        cnames: ~
        allow.inf: no
        has.default: no
        default: ~
        trafo: ~
        requires: ~
        tunable: yes
        special.vals: []
      min_data_in_leaf:
        id: min_data_in_leaf
        type: integer
        len: 1
        lower: 1
        upper: 10000
        values: ~
        cnames: ~
        allow.inf: no
        has.default: no
        default: ~
        trafo: ~
        requires: ~
        tunable: yes
        special.vals: []
      lambda_l1:
        id: lambda_l1
        type: numeric
        len: 1
        lower: 0.0
        upper: 100.0
        values: ~
        cnames: ~
        allow.inf: no
        has.default: no
        default: ~
        trafo: ~
        requires: ~
        tunable: yes
        special.vals: []
      lambda_l2:
        id: lambda_l2
        type: numeric
        len: 1
        lower: 0.0
        upper: 100.0
        values: ~
        cnames: ~
        allow.inf: no
        has.default: no
        default: ~
        trafo: ~
        requires: ~
        tunable: yes
        special.vals: []
    forbidden: ~
  iteraciones: 100.0
lgbm:
  param_fijos:
    boosting: gbdt
    objective: binary
    metric: auc
    first_metric_only: no
    boost_from_average: yes
    feature_pre_filter: no
    force_row_wise: yes
    verbosity: -100.0
    seed: 200003.0
    max_depth: -1
    min_gain_to_split: 0.0
    min_sum_hessian_in_leaf: 0.001
    lambda_l1: 0.0
    lambda_l2: 0.0
    max_bin: 31
    bagging_fraction: 1.0
    pos_bagging_fraction: 1.0
    neg_bagging_fraction: 1.0
    is_unbalance: no
    scale_pos_weight: 1.0
    drop_rate: 0.1
    max_drop: 50.0
    skip_drop: 0.5
    extra_trees: no
    num_iterations: 1200.0
    learning_rate: 0.02
    feature_fraction: 0.5
    num_leaves: 750.0
    min_data_in_leaf: 10000.0
    early_stopping_round: 100.0
out:
  lgbm:
    mejores_hiperparametros:
      num_leaves: 1496
      num_iterations: 2468
      learning_rate: 0.0394181
      feature_fraction: 0.4684899
      min_data_in_leaf: 14
      lambda_l1: 0.0698877
      lambda_l2: 19.8786334
    'y': 0.9389194
